export enum IconAppName {
  MAIL = "Mail",
  PHONE = "Phone",
  DOWNLOAD = "Download",
  FORWARD = "Forward",
  HOME = "Home",
  ABOUT = "About",
  PROJECTS = "Projects",
  STACK = "Stack",
  CONTACT = "Contact",
  CHECKMARK = "Checkmark",
  CLOSE = "Close",
  ARROW = "Arrow",
  TELEGRAM = "Telegram",
  INSTAGRAM = "Instagram",
  LINKEDIN = "Linkedin",
  GITHUB = "Github",
}
